# templates names
ACCOUNT_WAS_RECOVERED_EMAIL_TEMPLATE = "ACCOUNT_WAS_RECOVERED_EMAIL_TEMPLATE"
USER_PASSWORD_RESET_EMAIL_TEMPLATE = "USER_PASSWORD_RESET_EMAIL_TEMPLATE"  # noqa
USER_ACCOUNT_VERIFICATION_EMAIL_TEMPLATE = "USER_ACCOUNT_VERIFICATION_EMAIL_TEMPLATE"
ACCOUNT_SCHEDULED_FOR_DELETION_TEMPLATE_NAME = (
    "ACCOUNT_SCHEDULED_FOR_DELETION_TEMPLATE_NAME"
)
ACCOUNT_WAS_DELETED_EMAIL_TEMPLATE = "ACCOUNT_WAS_DELETED_EMAIL_TEMPLATE"
ACCOUNT_INFO_ASKED_FOR_TEMPLATE = "ACCOUNT_INFO_ASKED_FOR_TEMPLATE"
ACCOUNT_INFO_IS_READY_TEMPLATE = "ACCOUNT_INFO_IS_READY_TEMPLATE"
