USER_API_URL_NAME = "user_me"
USER_REGISTRATION_URL_NAME = "user_register"
TOKEN_AUTH_URL_NAME = "token_auth"
REFRESH_TOKEN_URL_NAME = "token_refresh"
TOKEN_VERIFY_URL_NAME = "token_verify"
LOGOUT_URL_NAME = "rest_logout"
PASS_RESET_URL_NAME = "rest_password_reset"
PASS_RESET_CONFIRM_URL_NAME = "rest_password_reset_confirm"
