# Generated by Django 2.2.9 on 2020-01-30 15:22

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="privacy_policy",
            field=models.BooleanField(
                default=True, verbose_name="Privacy policy accepted"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="security_hash",
            field=models.UUIDField(
                default=uuid.uuid4, unique=True, verbose_name="Security hash"
            ),
        ),
    ]
