# Generated by Django 2.2.10 on 2020-02-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0002_user_auth_fields")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_info_link",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="Account info link"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="account_info_sent",
            field=models.BooleanField(
                default=False, verbose_name="Account info has been sent"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Deleted"),
        ),
        migrations.AddField(
            model_name="user",
            name="last_account_info_created",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Account info link created date"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="warning_sent_email",
            field=models.CharField(
                choices=[
                    ("no_warnings", "No warnings"),
                    ("first_warning_sent", "First warning sent"),
                    ("second_warning_sent", "Second warning sent"),
                ],
                default="no_warnings",
                max_length=256,
                verbose_name="Warning email",
            ),
        ),
    ]
