# Generated by Django 2.2.10 on 2020-02-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0002_user_auth_fields")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Deleted"),
        ),
        migrations.AddField(
            model_name="user",
            name="warning_sent_email",
            field=models.CharField(
                choices=[
                    ("no_warnings", "No warnings"),
                    ("first_warning_sent", "First warning sent"),
                    ("second_warning_sent", "Second warning sent"),
                ],
                default="no_warnings",
                max_length=256,
                verbose_name="Warning email",
            ),
        ),
    ]
