# templates names
INACTIVE_ACCOUNT_DELETION_DONE_TEMPLATE = "INACTIVE_ACCOUNT_DELETION_DONE_TEMPLATE"
INACTIVE_ACCOUNT_DELETION_WARNING_TEMPLATE = (
    "INACTIVE_ACCOUNT_DELETION_WARNING_TEMPLATE"
)
