# templates names
ACCOUNT_WAS_DELETED_EMAIL_TEMPLATE = "ACCOUNT_WAS_DELETED_EMAIL_TEMPLATE"
INACTIVE_ACCOUNT_DELETION_DONE_TEMPLATE = "INACTIVE_ACCOUNT_DELETION_DONE_TEMPLATE"
INACTIVE_ACCOUNT_DELETION_WARNING_TEMPLATE = (
    "INACTIVE_ACCOUNT_DELETION_WARNING_TEMPLATE"
)
